### ISSUE TITLE
config.json and cache.son are not being created or populated

### ISSUE THREAD

**Issue by HelloChrisBrown** [jason0x43/alfred-redmine#1] opened 2015-01-07 23:37 UTC
These files are not being created and causing the below error. I tried creating the files manually thinking they would be populated by the setup, but that is not the case.

[ERROR: alfred.workflow.input.scriptfilter] Code 0: 2015/01/07 17:36:44 Using config file /Users/cb/Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-redmine/config.json
2015/01/07 17:36:44 Using cache file /Users/cb/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.jason0x43.alfred-redmine/cache.json
2015/01/07 17:36:44 Error loading config: open /Users/cb/Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-redmine/config.json: no such file or directory
2015/01/07 17:36:44 Error loading cache: open /Users/cb/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.jason0x43.alfred-redmine/cache.json: no such file or directory
2015/01/07 17:36:44 args: []string{"./alfred-redmine", "tell", ""}
2015/01/07 17:36:44 op: 'tell'
2015/01/07 17:36:44 kind: ''
2015/01/07 17:36:44 query: ''

**Comment by jason0x43** [comment] 2015-01-16 03:39
Confirmed. Working on it...

**Comment by jason0x43** [comment] 2015-01-16 03:42
Well, the problem isn't so much that it can't read those files as that it should be presenting the login option.

**Comment by jason0x43** [comment] 2015-01-16 06:08
This is fixed in [version 1.1.0](https://github.com/jason0x43/alfred-redmine/releases/tag/v1.1.0).

**Closed as completed by jason0x43** 2015-01-16 06:08 UTC
Labels: bug
